---
title: "CSCI340-Final"
author: "Darlyn Close"
date: "5/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load, include=FALSE}
#NOTE: csv files must be downloaded on computer
#Location of file must be input into read.csv function

ext2large <- read.csv("C:/Location/of/file/ext2large.csv")

ext2small <- read.csv("C:/Location/of/file/ext2small.csv")

ext4large <- read.csv("C:/Location/of/file/ext4large.csv")

ext4small <- read.csv("C:/Location/of/file/ext4small.csv")

fat32small <- read.csv("C:/Location/of/file/fat32small.csv")

fat32large <- read.csv("C:/Location/of/file/fat32large.csv")

ntfslarge <- read.csv("C:/Location/of/file/ntfslarge.csv")

ntfssmall <- read.csv("C:/Location/of/file/ntfssmall.csv")

xfslarge <- read.csv("C:/Location/of/file/xfslarge.csv")

xfssmall <- read.csv("C:/Location/of/file/xfssmall.csv")
```

Calculations for ext2 large files
```{r}
#ext2 large standard deviation
print(ext2.l.s <- sd(ext2large$speed))

#ext2 large mean
print(ext2.l.x <- mean(ext2large$speed))

#ext2 large standard error
print(ext2.l.se <- 1.96*ext2.l.s/sqrt(250))

#ext2 large confidence interval
print(ext2.l.ci <- c(ext2.l.x - ext2.l.se, ext2.l.x + ext2.l.se))
```

Calculations for ext2 small files
```{r}
#ext2 small standard deviation
print(ext2.s.s <- sd(ext2small$speed))

#ext2 small mean
print(ext2.s.x <- mean(ext2small$speed))

#ext2 small standard error
print(ext2.s.se <- 1.96*ext2.s.s/sqrt(500))

#ext2 small confidence interval
print(ext2.s.ci <- c(ext2.s.x - ext2.s.se, ext2.s.x + ext2.s.se))
```

Calculations for ext4 large files
```{r}
#ext4 large standard deviation
print(ext4.l.s <- sd(ext4large$speed))

#ext4 large mean
print(ext4.l.x <- mean(ext4large$speed))

#ext4 large standard error
print(ext4.l.se <- 1.96*ext4.l.s/sqrt(250))

#ext4 large confidence interval
print(ext4.l.ci <- c(ext4.l.x - ext4.l.se, ext4.l.x + ext4.l.se))
```

Calculations for ext4 small files
```{r}
#ext4 small standard deviation
print(ext4.s.s <- sd(ext4small$speed))

#ext4 small mean
print(ext4.s.x <- mean(ext4small$speed))

#ext4 small standard error
print(ext4.s.se <- 1.96*ext4.s.s/sqrt(500))

#ext4 small confidence interval
print(ext4.s.ci <- c(ext4.s.x - ext4.s.se, ext4.s.x + ext4.s.se))
```

Calculations for fat32 large files
```{r}
#fat32 large standard deviation
print(fat32.l.s <- sd(fat32large$speed))

#fat32 large mean
print(fat32.l.x <- mean(fat32large$speed))

#fat32 large standard error
print(fat32.l.se <- 1.96*fat32.l.s/sqrt(250))

#fat32 large confidence interval
print(fat32.l.ci <- c(fat32.l.x - fat32.l.se, fat32.l.x + fat32.l.se))
```

Calculations for fat32 small files
```{r}
#fat32 small standard deviation
print(fat32.s.s <- sd(fat32small$speed))

#fat32 small mean
print(fat32.s.x <- mean(fat32small$speed))

#fat32 small standard error
print(fat32.s.se <- 1.96*fat32.s.s/sqrt(500))

#fat32 small confidence interval
print(fat32.s.ci <- c(fat32.s.x - fat32.s.se, fat32.s.x + fat32.s.se))
```

Calculations for NTFS large files
```{r}
#ntfs large standard deviation
print(ntfs.l.s <- sd(ntfslarge$speed))

#ntfs large mean
print(ntfs.l.x <- mean(ntfslarge$speed))

#ntfs large standard error
print(ntfs.l.se <- 1.96*ntfs.l.s/sqrt(250))

#ntfs large confidence interval
print(ntfs.l.ci <- c(ntfs.l.x - ntfs.l.se, ntfs.l.x + ntfs.l.se))
```

Calculations for NTFS small files
```{r}
#ntfs small standard deviation
print(ntfs.s.s <- sd(ntfssmall$speed))

#ntfs small mean
print(ntfs.s.x <- mean(ntfssmall$speed))

#ntfs small standard error
print(ntfs.s.se <- 1.96*ntfs.s.s/sqrt(500))

#ntfs small confidence interval
print(ntfs.s.ci <- c(ntfs.s.x - ntfs.s.se, ntfs.s.x + ntfs.s.se))
```

Calculations for XFS large files
```{r}
#xfs large standard deviation
print(xfs.l.s <- sd(xfslarge$speed))

#xfs large mean
print(xfs.l.x <- mean(xfslarge$speed))

#xfs large standard error
print(xfs.l.se <- 1.96*xfs.l.s/sqrt(250))

#xfs large confidence interval
print(xfs.l.ci <- c(xfs.l.x - xfs.l.se, xfs.l.x + xfs.l.se))
```

Calculations for XFS small files
```{r}
#xfs small standard deviation
print(xfs.s.s <- sd(xfssmall$speed))

#xfs small mean
print(xfs.s.x <- mean(xfssmall$speed))

#xfs small standard error
print(xfs.s.se <- 1.96*xfs.s.s/sqrt(500))

#xfs small confidence interval
print(xfs.s.ci <- c(xfs.s.x - xfs.s.se, xfs.s.x + xfs.s.se))
```

